"""Central configuration for the arXiv semantic search engine.

Keeping every tunable value here means you change behaviour in one place
instead of hunting through the logic. Anything you might reasonably want to
adjust — the model, how many papers to index, where files are saved — lives
in this file.
"""

from pathlib import Path

# --- Model ---
# The sentence-transformer used to turn abstracts into vectors.
# all-MiniLM-L6-v2 is small (~90MB), fast on CPU, and produces 384-dim vectors.
MODEL_NAME = "all-MiniLM-L6-v2"
EMBEDDING_DIM = 384  # output dimension of the model above

# --- Dataset ---
# Source dataset on Hugging Face and how many abstracts to index.
# Set DATASET_SIZE to None to use the full dataset (~117K papers).
DATASET_NAME = "CShorten/ML-ArXiv-Papers"
DATASET_SIZE = 20000

# --- Storage ---
# Where the built index and its paper metadata are saved. These are
# regenerated by build_index.py, so they're git-ignored.
DATA_DIR = Path("data")
INDEX_PATH = DATA_DIR / "abstracts.index"
METADATA_PATH = DATA_DIR / "abstracts.pkl"

# --- Search ---
# Default number of results to return per query.
DEFAULT_TOP_K = 5
